### ISSUE TITLE
Kubernetes example and Grafana dashboard

### ISSUE THREAD

**Issue by andresterba** [hipages/php-fpm_exporter#104]
First of all, thanks for the exporter :tada: 
It works perfect in my setup!

As there is currently no documentation how to get started within k8s I have created [a simple example](https://github.com/andresterba/k8s-php-exporter).

I have also adjusted the Grafana dashboard a bit as some parts did not work (some queries used `container_name` instead of `container`).
I am not so sure if this is specific to my setup or something changed with Prometheus/Exporters/Grafana.

If this is just broken at the moment is there any way I can contribute to the dashboard?

**Comment by estahn** [comment]
@andresterba I was meant to create some documentation on how to run it in Kubernetes but never came around it. So great effort!

The Grafana dashboard as published was too tightly coupled to our internal labels. Cleaning it up and putting it into the repository would be helpful for many I believe.

I'm accepting pull requests.

**Comment by webframp** [comment]
Would greatly appreciate this too. Doing some early testing now and trying to sort out what further customization I'll need to do to the grafana dashboard. The "dependencies on internal branch deployment" are a bit unclear.

**Comment by andresterba** [comment]
I've created this PR https://github.com/hipages/php-fpm_exporter/pull/106 with a more generic dashboard.
For now it provides only a namespace filter.

**Comment by perriea** [comment]
Any news ?
