### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by insekticid** [hipages/php-fpm_exporter#12]
Hi,
I am looking for Grafana Dashboard config for your metrics. Something like https://grafana.com/dashboards/3901

**Comment by estahn** [comment]
@insekticid We're looking at releasing one fairly soon. We're still working out 1 or 2 issues. I will attach a dev version and it currently looks like this:

![fireshot capture 3 - grafana - kubernetes php-fpm_ - https___grafana k8s hipages com au_](https://user-images.githubusercontent.com/362174/36763045-72729a8c-1c7a-11e8-9fd1-1462e2159f76.png)
[Kubernetes PHP-FPM-1519777730526.json.zip](https://github.com/hipages/php-fpm_exporter/files/1765170/Kubernetes.PHP-FPM-1519777730526.json.zip)

**Comment by insekticid** [comment]
you are GOD!! will test it today

**Comment by estahn** [comment]
@insekticid I have published the updated dashboard here: https://grafana.com/dashboards/4912

It's working based on v0.4.0 which contains some additional metrics.

You most likely will need to remove `hip_new` from the queries. It's related to our branch deploy setup but I'm trying to make it more general.

The dashboard also assumes the name of your php-fpm container is `fpm` (see queries). I will adjust this in the next revision.

**Comment by estahn** [comment]
@insekticid Will close this issue. Feel free to reopen it with questions/suggestions.

**Comment by IppX** [comment]
> @insekticid I have published the updated dashboard here: https://grafana.com/dashboards/4912
> 
> It's working based on v0.4.0 which contains some additional metrics.
> 
> You most likely will need to remove `hip_new` from the queries. It's related to our branch deploy setup but I'm trying to make it more general.
> 
> The dashboard also assumes the name of your php-fpm container is `fpm` (see queries). I will adjust this in the next revision.
> 
> Let me know your thoughts or any suggestions you may have.

Hi and thanks for this exporter and dashboard they're very useful.

I came across this issue while trying to get the dashboard to work.
I slightly adapted it to remove the dependency to `branch`, using the `app` variable in queries which is the standard naming convention of deployment/replicaset/pods when using helm for example.
It still assumes that the php containers are suffixed with `-php` though. And you might have to change `pod=` to `kubernetes_pod=` depending on your prometheus config.

You can find it here: https://gist.github.com/IppX/970e3109012ef03390242a72144b19a6
