### ISSUE TITLE
 What difference between Running Process and Active Process 

### ISSUE THREAD

**Issue by phutoan31299** [hipages/php-fpm_exporter#131]
In metrics "phpfpm_process_state", I have seen the state "Running" but I wonder that what different between among running process, active process and finishing process?

**Comment by estahn** [comment]
@phutoan31299 Apologies, I have missed your issue.

I'm not quite sure about your question, so just let me know if I misunderstand. Just to clarify, do you mean you have seen `phpfpm_process_state` with a value `active`?

* `phpfpm_process_state` shows the state a process is in. The state can be one of these values: https://github.com/hipages/php-fpm_exporter/blob/4d2aa1a2afd3c11c9cf8ac6bde2fb429219c1839/phpfpm/phpfpm.go#L227-L235
* `active` on the other hand is not a specific state, but a sort of aggregate, e.g. state `running` means the process is active, state `finishing` means the process is active, state `idle` means the process is NOT active 

Hope that answers your question.
