### ISSUE TITLE
Error during shutdowncontext deadline exceeded

### ISSUE THREAD

**Issue by sungaohui** [hipages/php-fpm_exporter#132]
docker run -d --name fpm-exporter-01 -p 9253:9252 hipages/php-fpm_exporter:v2.0.1,when kill, exit code 1, logs is 'time="2021-02-03T03:44:55Z" level=fatal msg="Error during shutdowncontext deadline exceeded"'

**Comment by ossinkine** [comment]
Why this was closed if it still is not fixed?

**Comment by Spittal** [comment]
I too am getting this issue.
