### ISSUE TITLE
FPM_REQUEST_INFO changed in PHP 7.4

### ISSUE THREAD

**Issue by stchr** [hipages/php-fpm_exporter#137]
FPM_REQUEST_INFO changed from `Getting request informations` to `Getting request information` in PHP 7.4

See `[FPM_REQUEST_INFO] = "Getting request information"`, in https://github.com/php/php-src/blob/07fa13088e1349f4b5a044faeee57f2b34f6b6e4/sapi/fpm/fpm/fpm_request.c#L27

In PHP >= 7.4 you can get error messages like "Unknown process state 'Getting request information'" in php-fpm_exporter.
And indeed, "Getting request information" is unknown, as php-fpm_exporter is checking for "Getting request informations" (note the wrong plural "s"), which was correct for PHP < 7.4

This was changed in PHP >= 7.4 with php/php-src@84b195d

**Comment by TestsLing** [comment]
It makes php-fpm_exporter not work
