### ISSUE TITLE
Add ability to allow or disable specific metrics

### ISSUE THREAD

**Issue by blkperl** [hipages/php-fpm_exporter#175]
Would there be any interest in new configuration that allows the users to choose which metrics are sent by the exporter? I can submit a pull request.

In my use case we have thousands of pods running php-fpm and we have exceeded our quota for metrics so we want to restrict the metrics sent to the ones that are needed. 

I would also be interested in #84 being completed.

**Comment by blkperl** [comment]
I've learned that prometheus filtering has an `action: drop` that can be used to accomplish the same thing.

**Comment by estahn** [comment]
@blkperl I think it's a good suggestion and at times more trivial compared to adjusting the scrape config. But yes Prometheus allows dropping of metrics during scraping: https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus
