### ISSUE TITLE
alternative docker registry

### ISSUE THREAD

**Issue by philipp-hb** [hipages/php-fpm_exporter#199]
more and more companies are moving away from docker hub due to the new licensing.
Is there another docker registry where one can download your images? If not, I'd suggest to provide one

**Comment by torbendury** [comment]
Is there anything happening regarding this topic? It's a PITA running into `ImagePullBackOff` issues due to Docker Inc. rate limits.

**Comment by estahn** [comment]
This is now being pushed to GHCR.

https://github.com/hipages/php-fpm_exporter/pkgs/container/php-fpm_exporter

**Comment by torbendury** [comment]
Hi @estahn and thank you for realizing this!

However it seems the containers are pushed privately:

```bash
$ docker pull ghcr.io/hipages/php-fpm_exporter:2.2.0-amd64
Error response from daemon: Head https://ghcr.io/v2/hipages/php-fpm_exporter/manifests/2.2.0-amd64: unauthorized

```

**Comment by estahn** [comment]
Shameless plug: If you experience docker pull issues maybe give this a try https://github.com/estahn/k8s-image-swapper

**Comment by estahn** [comment]
@torbendury You should have access now.
