### ISSUE TITLE
docker hub arm image

### ISSUE THREAD

**Issue by ThorstenEngel** [hipages/php-fpm_exporter#203]
Hi there! 

Thanks for the greate work and for adding arm64 support. Do you have time to add a docker-hub image for arm as well? This would simplify it a lot for me ;-)

Thank you in advance!

Thorsten

**Comment by sirantd** [comment]
Hi. I was looking for the same. I've built a multi-arch [version](https://hub.docker.com/repository/docker/opsworksco/php-fpm_exporter) for myself and it's working fine. I created this PR which should automate releasing of multi-arch images to docker hub https://github.com/hipages/php-fpm_exporter/pull/226

**Comment by gocd-matrix** [comment]
This sounds great. Unfortunately docker hub does not seem to have builded the arm image (hipages) yet.

**Comment by sirantd** [comment]
afaik, it should be available with next tag release, PR has been merged

**Comment by estahn** [comment]
@ThorstenEngel @sirantd https://github.com/hipages/php-fpm_exporter/pkgs/container/php-fpm_exporter

Is that solving it for you?

**Comment by sirantd** [comment]
@estahn Yep, I see that docker hub now has both linux/amd64 and linux/arm64

**Comment by gocd-matrix** [comment]
Yes! This solves it. Thank you, great!
