### ISSUE TITLE
Error while connecting using linux socket

### ISSUE THREAD

**Issue by MMarco94** [hipages/php-fpm_exporter#30]
Hi, I'm trying to colect php-fpm metrics using this command: `php-fpm_exporter get --phpfpm.scrape-uri unix:/var/run/php/php7.2-fpm.sock;/status` 

Unfortunately, I get the following error:
`ERRO[0000] malformed MIME header line: Access to the script '' has been denied (see security.limit_extensions)`
Is there any way to use this software without removing the `security.limit_extensions` option on the php-fpm configuration, since it may be very dangerous?

**Comment by pampy** [comment]
Just in case someone finds this bug report by googling like me, I found the solution in a different ticket:
You need to put the URI in quotes like this:
`php-fpm_exporter get --phpfpm.scrape-uri 'unix:/var/run/php/php7.2-fpm.sock;/status'`
