### ISSUE TITLE
feat: Opcache metrics

### ISSUE THREAD

**Issue by estahn** [hipages/php-fpm_exporter#31]
...

Looking at [fpm_main.c](https://github.com/php/php-src/blob/master/sapi/fpm/fpm/fpm_main.c) it appears we cannot send PHP code directly via fcgi. PHP-PFM will need to have access to a PHP file that exposes the metrics.

### Functions

* `opcache_get_configuration()`
* `opcache_get_status()`

### References

* https://tideways.com/profiler/blog/fine-tune-your-opcache-configuration-to-avoid-caching-suprises
* https://www.digitalocean.com/community/questions/configure-tune-opcache-on-php7

**Comment by guilhem** [comment]
Opcache can be mesured with https://github.com/hipages/php-fpm_exporter/pull/290 merged.
