### ISSUE TITLE
ERRO[0000] invalid character 'N' looking for beginning of value

### ISSUE THREAD

**Issue by ZalemCitizen** [hipages/php-fpm_exporter#34]
Hello, 

I can't scrape on a unix socket (running commands as root) : 

> php-fpm_exporter get --phpfpm.scrape-uri unix:///run/php/php7.1-fpm-www.sock;/status --log.level debug
**> ERRO[0000] invalid character 'N' looking for beginning of value**
> Address:                unix:///run/php/php7.1-fpm-www.sock
> Pool:
> Start time:             Mon, 01 Jan 0001 00:00:00 +0000
> Start since:            0
> Accepted connections:   0
> Listen Queue:           0
> Max Listen Queue:       0
> Listen Queue Length:    0
> Idle Processes:         0
> Active Processes:       0
> Total Processes:        0
> Max active processes:   0
> Max children reached:   0
> Slow requests:          0
> 
> bash: /status: Aucun fichier ou dossier de ce type

where there is no pb when using a fci port : 

> php-fpm_exporter get --phpfpm.scrape-uri tcp://127.0.0.1:9000/status
> Address:                tcp://127.0.0.1:9000/status
> Pool:                   www
> Start time:             Mon, 22 Oct 2018 00:48:02 +0200
> Start since:            30772
> Accepted connections:   13
> Listen Queue:           0
> Max Listen Queue:       0
> Listen Queue Length:    128
> Idle Processes:         2
> Active Processes:       1
> Total Processes:        3
> Max active processes:   2
> Max children reached:   0
> Slow requests:          0

Can't figure what's going on.

**Comment by ZalemCitizen** [comment]
Adding a piece of info :
Using cgi-fcgi command, I can reach the /status on same unix socket, with same variables your scraper is using :

> SCRIPT_NAME=/status SCRIPT_FILENAME=/status REQUEST_METHOD=GET QUERY_STRING=full REMOTE_ADDR=127.0.0.1 cgi-fcgi -bind -connect /run/php/php7.1-fpm-www.sock
> Expires: Thu, 01 Jan 1970 00:00:00 GMT
> Cache-Control: no-cache, no-store, must-revalidate, max-age=0
> Content-type: text/plain;charset=UTF-8
> 
> pool:                 www
> process manager:      dynamic
> start time:           22/Oct/2018:09:07:14 +0200
> start since:          2934
> accepted conn:        13
> listen queue:         0
> max listen queue:     0
> listen queue len:     0
> idle processes:       2
> active processes:     1
> total processes:      3
> max active processes: 2
> max children reached: 0
> slow requests:        0
> 
> ************************
> pid:                  18160
> state:                Idle
> ...

**Comment by herb123456** [comment]
what is your environment?

os?php version?

**Comment by ZalemCitizen** [comment]
Ubuntu 16.04 lts
PHP 7.1

**Comment by dbzmelvin** [comment]
i have the same problem, Ubuntu 16.04 PHP 7.1

**Comment by ZalemCitizen** [comment]
Hello estahn, great news.
I'm sorry I don't know the command to make a build from your sources.

**Comment by estahn** [comment]
@ZalemCitizen I'm not sure what you mean. You can use the last tagged version (**v0.5.3**).

**Comment by estahn** [comment]
@ZalemCitizen Thanks, I have missed that the artefacts weren't deployed. CircleCI [failed](https://circleci.com/gh/hipages/php-fpm_exporter/216) due to the deploy step not being on go 1.11.

I have rectified this now and you will find the assets attached to the release.

**Comment by ZalemCitizen** [comment]
Ok, I've run my tests and it seems there is still a problem with UNIX socket : 

With php-fpm_exporter (ran as root), I get : 

    $ ./php-fpm_exporter version
    php-fpm_exporter 0.5.3, commit 8b64a58900a3a599ce1c0086951e478998dc6b3e, built at 2018-12-30T22:59:52Z
    $ ./php-fpm_exporter get --phpfpm.scrape-uri unix:///run/php/php7.1-fpm-www.sock;/status --log.level debug
    ERRO[0000] Pool[unix:///run/php/php7.1-fpm-www.sock]: No input file specified.
    ERRO[0000] invalid character 'N' looking for beginning of value
    Address:                unix:///run/php/php7.1-fpm-www.sock
    Pool:
    Start time:             Mon, 01 Jan 0001 00:00:00 +0000
    Start since:            0
    Accepted connections:   0
    Listen Queue:           0
    Max Listen Queue:       0
    Listen Queue Length:    0
    Idle Processes:         0
    Active Processes:       0
    Total Processes:        0
    Max active processes:   0
    Max children reached:   0
    Slow requests:          0
    
    bash: /status: Aucun fichier ou dossier de ce type`

Using simple cgi-fcgi command (ran as root) I get : 

    $ SCRIPT_NAME=/status \
       SCRIPT_FILENAME=/status \
       REQUEST_METHOD=GET \
       cgi-fcgi -bind -connect /run/php/php7.1-fpm-www.sock
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Cache-Control: no-cache, no-store, must-revalidate, max-age=0
    Content-type: text/plain;charset=UTF-8
    
    pool:                 www
    process manager:      dynamic
    start time:           31/Dec/2018:10:17:37 +0100
    start since:          2642
    accepted conn:        51
    listen queue:         0
    max listen queue:     0
    listen queue len:     0
    idle processes:       2
    active processes:     1
    total processes:      3
    max active processes: 2
    max children reached: 0
    slow requests:        0

**Comment by estahn** [comment]
@ZalemCitizen I just tested it and the issue you are experiencing is shell related. The shell will interpret the semicolon as the ending of the command, hence you will need to either escape or quote argument.

This should give you what you want:
```bash
./php-fpm_exporter get --phpfpm.scrape-uri "unix:///run/php/php7.1-fpm-www.sock;/status" --log.level debug
```

**Comment by ZalemCitizen** [comment]
Damn!
Many thanks for this simple trick, it works :

    $ ./php-fpm_exporter get --phpfpm.scrape-uri "unix:///run/php/php7.1-fpm-www.sock;/status"
    Address:                unix:///run/php/php7.1-fpm-www.sock;/status
    Pool:                   www
    Start time:             Mon, 31 Dec 2018 10:17:37 +0100
    Start since:            257275
    Accepted connections:   4674
    Listen Queue:           0
    Max Listen Queue:       0
    Listen Queue Length:    0
    Idle Processes:         2
    Active Processes:       1
    Total Processes:        3
    Max active processes:   3
    Max children reached:   0
    Slow requests:          0
