### ISSUE TITLE
Can't connect to unix socket file

### ISSUE THREAD

**Issue by wsilva** [hipages/php-fpm_exporter#60]
I am having a bad time trying to run it connecting to the unix socket file.

The log whe I try to scrape:

```txt
exporter_1    | time="2019-06-18T17:25:47Z" level=error msg="dial unix :: connect: no such file or directory"
```

I am using version `1.0.0` and I have already checked https://github.com/hipages/php-fpm_exporter/issues/19 but with no success.

To reproduce it I have forked the project and pushed the changes to different branch so if everything runs fine I can submit a pull request with the unix socket file example.

The test is available here: https://github.com/wsilva/php-fpm_exporter/tree/unix-socket-test/test just `docker-compose up` or `docker-compose up -d` and check the logs

To check the changes I made from the version `1.0.0`:

```bash
git diff v1.0.0..unix-socket-test
```

Please help, I have no idea about what I am missing.

**Comment by wsilva** [comment]
I have also tried using `/tmp` in case it has relation to permission/ownership of the socket file no success either

**Comment by wsilva** [comment]
Looks like the process started with the right parameters:

```bash
$ docker-compose exec exporter ash
/ # ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/php-fpm_exporter server --phpfpm.scrape-uri unix:///tmp/php.sock;/php-fpm-status
   49 root       0:00 ash
   57 root       0:00 ps aux
/ #
```

I have also tried using env vars instead of custom startup command:

```bash
$ docker-compose exec exporter ash
/ # ps aux
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/php-fpm_exporter server
   11 root       0:00 ash
   17 root       0:00 ps aux
/ # env
HOSTNAME=06d33b5027b4
SHLVL=1
HOME=/root
TERM=xterm
PHP_FPM_SCRAPE_URI=unix:///tmp/php.sock;/php-fpm-status
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ #
/ #
```

**Comment by wsilva** [comment]
Was not able to run with docker but able to run both process in the same machine, so I asked to reopen: https://github.com/hipages/php-fpm_exporter/issues/46

**Comment by Gravelandmp3** [comment]
i have the same issue :(
