### ISSUE TITLE
Not an issue - Thanks + Ansible role

### ISSUE THREAD

**Issue by VoidAndAny** [hipages/php-fpm_exporter#68]
Thanks for your job, this exporter is far more powerfull then the one listed on Prometheus exporters page...
For your information, I just published an Ansible role the deploy your exporter.
https://github.com/umanit/ansible-prometheus_phpfpm_exporter

**Comment by estahn** [comment]
@VoidAndAny Thanks. Do you mind if I add the link to our `README.md`?

**Comment by VoidAndAny** [comment]
As you want and thanks
